name: CI/CD Deployment

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. (Optional) Build or test your project
      - name: Build Project
        run: |
          echo "Building the project..."
          # Uncomment and customize the following commands if needed:
          # npm install
          # npm run build

      # 3. Deploy to the server via SSH
      - name: Deploy to Server
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: ${{ secrets.SERVER_PORT }}  # Omit this line if you're using the default port 22
          script: |
            cd /var/apps/ec-test.asia-hd.com  # Replace with your actual project path on the server
            git pull origin main
            # Optionally, add commands to restart your application, clear caches, etc.
